image: gitpod/workspace-full

ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    python3 manage.py migrate && 
    python3 manage.py test
  command: >
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        master: true
        addLabel: prebuilt-in-gitpod
        
